Enrollment No.: 240840116030



 Practical-2: Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas

step 1 : import the pandas library

In [ ]:
import pandas as pd

step 2 : create sample data

In [ ]:
# Create a dictionary containing student details such as ID, Name, Age, City, and Marks.
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Rahul", "Priya", "Amit", None, "Riya", "Ajay", "Naresh", "Jenil"],
    "Age": [20, 21, None, 20, 20, 22, 23, 28 ],
    "City": ["Surat", "Ahemdabad", "Surat", "Vadodara", "Gandhinagar", "Surat", "Ahemdabad" , "Vapi"],
    "Marks": [89, None, 75, 84, 94, 81, 90, 93]
}

step 3 : Inspect the database

In [ ]:
# Convert the dictionary into a Pandas DataFrame for easier data manipulation.
df = pd.DataFrame(data)

df

    ID    Name   Age         City  Marks
0  101   Rahul  20.0        Surat   89.0
1  102   Priya  21.0    Ahemdabad    NaN
2  103    Amit   NaN        Surat   75.0
3  104    None  20.0     Vadodara   84.0
4  105    Riya  20.0  Gandhinagar   94.0
5  106    Ajay  22.0        Surat   81.0
6  107  Naresh  23.0    Ahemdabad   90.0
7  108   Jenil  28.0         Vapi   93.0

In [ ]:
# task 1 : Display the first five rows of the dataset.
# head() is useful for quickly previewing the data.

df.head()

    ID   Name   Age         City  Marks
0  101  Rahul  20.0        Surat   89.0
1  102  Priya  21.0    Ahemdabad    NaN
2  103   Amit   NaN        Surat   75.0
3  104   None  20.0     Vadodara   84.0
4  105   Riya  20.0  Gandhinagar   94.0

In [ ]:
# task 2 : Display the last five rows of dataset.
# tail() helps check the ending records.

df.tail()

    ID    Name   Age         City  Marks
3  104    None  20.0     Vadodara   84.0
4  105    Riya  20.0  Gandhinagar   94.0
5  106    Ajay  22.0        Surat   81.0
6  107  Naresh  23.0    Ahemdabad   90.0
7  108   Jenil  28.0         Vapi   93.0

In [ ]:
# task 3 : Display detail information about the dataset.
# info() shows the number of rows, columns, data types, and missing values.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    8 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
# task 4 : generate statistical information for numerical columns.
# describe() calculates count, mean, standard deviation, minimum, maximum, and quartiles.

df.describe()

              ID        Age      Marks
count    8.00000   7.000000   7.000000
mean   104.50000  22.000000  86.571429
std      2.44949   2.886751   6.900656
min    101.00000  20.000000  75.000000
25%    102.75000  20.000000  82.500000
50%    104.50000  21.000000  89.000000
75%    106.25000  22.500000  91.500000
max    108.00000  28.000000  94.000000

In [ ]:
# task 5 : Display the dimenssion of dataset
# shape returns the number of rows and columns.

df.shape

(8, 5)

In [ ]:
# task 6 : Display the names of all columns in the dataframe.
# columns returns the column labels.

df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [ ]:
# task 7 : Display the data type of easch column.
# dtypes helps identify whether columns are integers, floats, strings, etc.

df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

step 4 : Check missing values

In [ ]:
# task 8 : check for missing value in every column.
# isnull() identifies missing values and sum() counts them.

df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [ ]:
# task 9 : replace missing values in the marks column.
# fillna() replaces missing values with the average (mean) marks.

df ["Marks"]=df["Marks"].fillna(df["Marks"].mean())
df

    ID    Name   Age         City      Marks
0  101   Rahul  20.0        Surat  89.000000
1  102   Priya  21.0    Ahemdabad  86.571429
2  103    Amit   NaN        Surat  75.000000
3  104    None  20.0     Vadodara  84.000000
4  105    Riya  20.0  Gandhinagar  94.000000
5  106    Ajay  22.0        Surat  81.000000
6  107  Naresh  23.0    Ahemdabad  90.000000
7  108   Jenil  28.0         Vapi  93.000000

In [ ]:
# task 10 :  replace missing values in the age column.
# Missing ages are replaced with the average age.

df ["Age"]=df["Age"].fillna(df["Age"].mean())
df

    ID    Name   Age         City      Marks
0  101   Rahul  20.0        Surat  89.000000
1  102   Priya  21.0    Ahemdabad  86.571429
2  103    Amit  22.0        Surat  75.000000
3  104    None  20.0     Vadodara  84.000000
4  105    Riya  20.0  Gandhinagar  94.000000
5  106    Ajay  22.0        Surat  81.000000
6  107  Naresh  23.0    Ahemdabad  90.000000
7  108   Jenil  28.0         Vapi  93.000000

In [ ]:
# task 11 : replace missing names with text 'unknown'.
# fillna() replaces blank names with a meaningful text value.

df ["Name"]=df["Name"].fillna("Unknown")
df

    ID     Name   Age         City      Marks
0  101    Rahul  20.0        Surat  89.000000
1  102    Priya  21.0    Ahemdabad  86.571429
2  103     Amit  22.0        Surat  75.000000
3  104  Unknown  20.0     Vadodara  84.000000
4  105     Riya  20.0  Gandhinagar  94.000000
5  106     Ajay  22.0        Surat  81.000000
6  107   Naresh  23.0    Ahemdabad  90.000000
7  108    Jenil  28.0         Vapi  93.000000

Step 5 : Detect duplicatr data

In [ ]:
# Task 12 : check whether each row is duplicated
# duplicated() returns True for duplicate rows and False otherwise.

df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
# task 13 : count the total number of duplicate row.
# sum() counts all True values returned by duplicated().

df.duplicated().sum()

np.int64(0)

step 6 : Remover duplicate records

In [ ]:
# task 14 : remove duplicate rows from the dataframe.
# drop_duplicates() keeps only unique records.

df = df.drop_duplicates()
df

    ID     Name   Age         City      Marks
0  101    Rahul  20.0        Surat  89.000000
1  102    Priya  21.0    Ahemdabad  86.571429
2  103     Amit  22.0        Surat  75.000000
3  104  Unknown  20.0     Vadodara  84.000000
4  105     Riya  20.0  Gandhinagar  94.000000
5  106     Ajay  22.0        Surat  81.000000
6  107   Naresh  23.0    Ahemdabad  90.000000
7  108    Jenil  28.0         Vapi  93.000000

step 7 : Rename column

In [ ]:
# task 15 : Rename column "Marks" to "Score".
# rename() changes the column name without affecting the data.

df.rename(columns={"Marks": "Score"}, inplace=True)
df

    ID     Name   Age         City      Score
0  101    Rahul  20.0        Surat  89.000000
1  102    Priya  21.0    Ahemdabad  86.571429
2  103     Amit  22.0        Surat  75.000000
3  104  Unknown  20.0     Vadodara  84.000000
4  105     Riya  20.0  Gandhinagar  94.000000
5  106     Ajay  22.0        Surat  81.000000
6  107   Naresh  23.0    Ahemdabad  90.000000
7  108    Jenil  28.0         Vapi  93.000000

step 8 : change the data type

In [ ]:
# task 16 : convert the age column from float to integer.
# astype(int) changes the data type to integer.

df["Age"]=df["Age"].astype(int)
df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

step 9 : create a new column

In [ ]:
# task 17 : create a new column named "Final Score".
# Add 5 bonus marks to each student's score.

df["Final Score"]=df["Score"]+5
df

    ID     Name  Age         City      Score  Final Score
0  101    Rahul   20        Surat  89.000000    94.000000
1  102    Priya   21    Ahemdabad  86.571429    91.571429
2  103     Amit   22        Surat  75.000000    80.000000
3  104  Unknown   20     Vadodara  84.000000    89.000000
4  105     Riya   20  Gandhinagar  94.000000    99.000000
5  106     Ajay   22        Surat  81.000000    86.000000
6  107   Naresh   23    Ahemdabad  90.000000    95.000000
7  108    Jenil   28         Vapi  93.000000    98.000000

step 10 : convert all letter to uppercase and lowercase.

In [ ]:
# task 18 :convert all students name to uppercase
# upper() means it coverts all letters in uppercase.
df["Name"]=df["Name"].str.upper()
df

    ID     Name  Age         City      Score  Final Score
0  101    RAHUL   20        Surat  89.000000    94.000000
1  102    PRIYA   21    Ahemdabad  86.571429    91.571429
2  103     AMIT   22        Surat  75.000000    80.000000
3  104  UNKNOWN   20     Vadodara  84.000000    89.000000
4  105     RIYA   20  Gandhinagar  94.000000    99.000000
5  106     AJAY   22        Surat  81.000000    86.000000
6  107   NARESH   23    Ahemdabad  90.000000    95.000000
7  108    JENIL   28         Vapi  93.000000    98.000000

In [ ]:
# task 19 :convert all City name to lowercase
# upper() means it coverts all letters in lowercase.
df["City"]=df["City"].str.lower()
df

    ID     Name  Age         City      Score  Final Score
0  101    rahul   20        surat  89.000000    94.000000
1  102    priya   21    ahemdabad  86.571429    91.571429
2  103     amit   22        surat  75.000000    80.000000
3  104  unknown   20     vadodara  84.000000    89.000000
4  105     riya   20  gandhinagar  94.000000    99.000000
5  106     ajay   22        surat  81.000000    86.000000
6  107   naresh   23    ahemdabad  90.000000    95.000000
7  108    jenil   28         vapi  93.000000    98.000000

step 11 : Remove leading and tralling spaces from city name

In [ ]:
# str.strip() removes leading and trailing whitespace.

df["City"]=df["City"].str.strip()
df

    ID     Name  Age         City      Score  Final Score
0  101    rahul   20        Surat  89.000000    94.000000
1  102    priya   21    Ahemdabad  86.571429    91.571429
2  103     amit   22        Surat  75.000000    80.000000
3  104  unknown   20     Vadodara  84.000000    89.000000
4  105     riya   20  Gandhinagar  94.000000    99.000000
5  106     ajay   22        Surat  81.000000    86.000000
6  107   naresh   23    Ahemdabad  90.000000    95.000000
7  108    jenil   28         Vapi  93.000000    98.000000

step 12 : sort the dataframe based on the "Final Score" column

In [ ]:
# Highest scoring students appear first.

df.sort_values(by="Final Score", ascending=False)

    ID     Name  Age         City      Score  Final Score
4  105     riya   20  gandhinagar  94.000000    99.000000
7  108    jenil   28         vapi  93.000000    98.000000
6  107   naresh   23    ahemdabad  90.000000    95.000000
0  101    rahul   20        surat  89.000000    94.000000
1  102    priya   21    ahemdabad  86.571429    91.571429
3  104  unknown   20     vadodara  84.000000    89.000000
5  106     ajay   22        surat  81.000000    86.000000
2  103     amit   22        surat  75.000000    80.000000

step 13 : save the  cleaned the dataframe as a new CSV file

In [ ]:
# index=False prevents row numbers from being saved in the CSV file.

df.to_csv("Cleaned_students.csv", index=False)
print("Dataset saved successfully.")

Dataset saved successfully.