Enrollment No.: 240840116030

Practical-1

AIM : Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON ƒles using Pandas.

step 1: import the pandas library

In [ ]:
# Pandas is used to create, read, modify, and analyze tabular data.
import pandas as pd

step 2: Create a sample data

In [ ]:
# Create a dictionary containing student details such as ID, Name, Age, City, and Marks.
data = {
    "ID": [101, 120, 103, 104, 105, 106],
    "Name": ["Rahul", "Priya", "Rajan", "Krisha", "Ruchi", "Dhruvil"],
    "Age": [20, 21, 13, 20, 22, 20 ],
    "City": ["Surat", "Ahemdabad", "Surat", "Vadodara", "Gandhinagar", "Surat"],
    "Marks": [89, 95, 75, 84, 96, 74]
}

step 3 : create a dataframe

In [ ]:
# Convert the dictionary into a Pandas DataFrame for easier data manipulation.
df = pd.DataFrame(data)

df

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  120    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

step 4: Save data as a CSV file

In [ ]:
# Export the DataFrame to a CSV file without including the index column.

df.to_csv("students.csv", index=False)

print("CSV file created successfully.")

CSV file created successfully.

step 5 : Save data as a excel file

In [ ]:
# Export the DataFrame to an Excel (.xlsx) file.

df.to_excel("students.xlsx", index=False)
print("Excel file created successfully.")

Excel file created successfully.

step 6 : Save data as a JSON file

In [ ]:
# Export the DataFrame to a JSON file using record-oriented format.

df.to_json("students.json", orient="records", index=4)
print("JSON file created successfully.")

JSON file created successfully.

step 7: raed the CSV file

In [ ]:
# Load the CSV file back into a DataFrame.
df_csv= pd.read_csv("students.csv")
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  120    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

step 8: raed the Excel file

In [ ]:
# Load the Excel file into a DataFrame.

df_excel = pd.read_excel("students.xlsx")
df_excel

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  120    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

step 9: raed the JSON file

In [ ]:
# Load the JSON file into a DataFrame.
df_json = pd.read_json("students.json")
df_json

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     89
1  120    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

step 10: Display the first five record

In [ ]:
# View the first five rows of the dataset using head().

df_csv.head()

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     89
1  120   Priya   21    Ahemdabad     95
2  103   Rajan   13        Surat     75
3  104  Krisha   20     Vadodara     84
4  105   Ruchi   22  Gandhinagar     96

step 11: Display the last five record

In [ ]:
# View the last five rows of the dataset using tail().

df_csv.tail()

    ID     Name  Age         City  Marks
1  120    Priya   21    Ahemdabad     95
2  103    Rajan   13        Surat     75
3  104   Krisha   20     Vadodara     84
4  105    Ruchi   22  Gandhinagar     96
5  106  Dhruvil   20        Surat     74

step 12: display dataset of information

In [ ]:
# Show the number of rows, columns, data types, and non-null values.
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Age     6 non-null      int64
 3   City    6 non-null      object
 4   Marks   6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

step 13 : Display Statistical summary

In [ ]:
# Generate summary statistics such as count, mean, minimum, maximum, and standard deviation.
df_csv.describe()

              ID        Age      Marks
count    6.00000   6.000000   6.000000
mean   106.50000  19.333333  85.500000
std      6.83374   3.204164   9.565563
min    101.00000  13.000000  74.000000
25%    103.25000  20.000000  77.250000
50%    104.50000  20.000000  86.500000
75%    105.75000  20.750000  93.500000
max    120.00000  22.000000  96.000000

step 14: Display dataset shape

In [ ]:
# Show the total number of rows and columns in the dataset.
df_csv.shape

(6, 5)

step 15 : Display column Names

In [ ]:
# List all the column names present in the DataFrame.
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

step 16 : Display data types

In [ ]:
# Show the data type of each column.
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

step 17 : check for any missing value

In [ ]:
# Count the number of missing (null) values in each column.
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

step 18 : display a single column

In [ ]:
# Retrieve and display only the 'Name' column.
df_csv["Name"]

0      Rahul
1      Priya
2      Rajan
3     Krisha
4      Ruchi
5    Dhruvil
Name: Name, dtype: object

step 19 : Display multiple columns

In [ ]:
# Retrieve and display the 'Name' and 'Marks' columns together.
df_csv[['Name', 'Marks']]

      Name  Marks
0    Rahul     89
1    Priya     95
2    Rajan     75
3   Krisha     84
4    Ruchi     96
5  Dhruvil     74

step 20 : filter records

In [ ]:
# Display only the students whose marks are greater than 80.
df_csv[df_csv['Marks'] > 80]

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     89
1  120   Priya   21    Ahemdabad     95
3  104  Krisha   20     Vadodara     84
4  105   Ruchi   22  Gandhinagar     96

step 21 : calculate the average marks

In [ ]:
# Compute the average (mean) marks of all students.
df_csv["Marks"].mean()

np.float64(85.5)

step 22: sort data

In [ ]:
# Arrange the student records in descending order based on marks.
df_csv.sort_values(by="Marks", ascending=False)

    ID     Name  Age         City  Marks
4  105    Ruchi   22  Gandhinagar     96
1  120    Priya   21    Ahemdabad     95
0  101    Rahul   20        Surat     89
3  104   Krisha   20     Vadodara     84
2  103    Rajan   13        Surat     75
5  106  Dhruvil   20        Surat     74