ENROLLMENT NUMBER : 240840116030

Practical 3

AIM : Apply filtering , sorting , aggregation and GroupBy operations on real-world dataset.

In [ ]:
import pandas as pd

In [ ]:
# Create a dictionary containing student details such as ID, Name, Department, City, Salary, Experience.
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Neha", "Vivek", "Pooja"],
    "Department": ["IT", "HR","IT", "Finance", "HR", "Finance", "IT", "HR"],
    "City": ["Surat", "Navsari", "Surat", "Valsad", "Surat", "Navsari", "Valsad", "Surat"],
    "Salary": [45000, 38000, 52000, 48000, 40000, 51000, 60000, 42000],
    "Experience": [2, 1, 5, 4, 2, 6, 8,3]
    }

In [ ]:
# Convert the dictionary into a Pandas DataFrame for easier data manipulation.
df = pd.DataFrame(data)

df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**step 1 : Display the dataset**

In [ ]:
# Display the complete dtaFrame

df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**step 2 : Filter data**

 Display Emplyoees from IT department.

In [ ]:
# The condition returns rows where Department is equal to "IT".

df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Display emplyoees with salary greater than 50000

In [ ]:
# Display emplyoees whose salary is greater than 50000.

df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Display Employees from surat

In [ ]:
# The condition returns rows where City is equal to "Surat".

df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Apply Multiple Conditions

In [ ]:
# Display emplyoees from It department
# having salary greater than 50000.

df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**step 3 : sort data**

Sort salary in ascending order

In [ ]:
# Sort employees by salary from lowest to highest.

df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Sort salary in Descending order

In [ ]:
# Sort employees by salary from highest to kowest.

df.sort_values(by="Salary", ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

sort by department and salary

In [ ]:
# First sort by department.
# Within easch department , sort salaries in descending order.

df.sort_values(by=["Department", "Salary"], ascending=[True, False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**step 4 : perform aggregation**

Calculate Total salary

In [ ]:
# Calculate the total salary of all employees.
df["Salary"].sum()

np.int64(376000)

Calculate Average Salary

In [ ]:
# Calculate the average salary.
df["Salary"].mean()

np.float64(47000.0)

Find Highest Salary

In [ ]:
# dilspay the maximum salary.
df["Salary"].max()

60000

Find lowest salary

In [ ]:
# Diplay the minimum salary.
df["Salary"].min()

38000

Count emplyoees

In [ ]:
# Count the total number of emplyoees.
df["Emp_ID"].count()

np.int64(8)

**step 5 : Perform GroupBy Operations**

Average salary department-wise

In [ ]:
# Group emplyoees based in Department.
# Calcutale the average salary of each department.

df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Minimum salary department-wise

In [ ]:
# Calculate the minimum salary of each department.
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Count salary department-wise

In [ ]:
# Calculate the total count salary of each department.
df.groupby("Department")["Salary"].count()

Department
Finance    2
HR         3
IT         3
Name: Salary, dtype: int64

Total salary department-wise

In [ ]:
# Calculate the total salary by each department.

df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Maximum Salary Department-wise

In [ ]:
# Calculate the maximum salary of each department.
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Average salary department-wise

In [ ]:
# Calculate the average salary of each department.
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Group by city

In [ ]:
# calculate the average salary of each city.
df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

**step 6 : Multiple Aggregation Functions**

In [ ]:
# apply multiple statistical functions.
# to the slary column for each department.
df.groupby("Department")["Salary"].agg(["count", "sum", "mean", "min", "max"])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**step 7 : save the result**

In [ ]:
# save the dataset into a CSV file.
df.to_csv("employee_data.csv", index=False)
print("Dataset saved successfully.")

Dataset saved successfully.

Dowmload the file

In [ ]:
# save the DataFrame as a CSV file
df.to_csv("employee_data.csv", index=False)

# Import the files module from google colab.
from google.colab import files

# Download the CSV file
files.download("employee_data.csv")

# to_csv() saved the Dataframe as a CSV file.
# files.download() prompts your browser to download the file.